// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4905.Galaktika.subsystems;

import org.usfirst.frc4905.Galaktika.RobotMap;
import org.usfirst.frc4905.Galaktika.Robot;

import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.DriverStation;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Solenoid;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Ramps extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final Solenoid solenoid1 = RobotMap.rampsSolenoid1;
    private final Solenoid solenoid2 = RobotMap.rampsSolenoid2;
    private final Solenoid solenoid3 = RobotMap.rampsSolenoid3;
    private final Solenoid solenoid4 = RobotMap.rampsSolenoid4;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final Solenoid releaseSolenoid1 = RobotMap.rampsSolenoidRelease1;
    private final Solenoid releaseSolenoid2 = RobotMap.rampsSolenoidRelease2;
    
    private boolean leftRampDeployed = false, rightRampDeployed = false;
    private static boolean safetiesEnabled;
    
    
    
    
    public void releaseRamps() {
    	releaseSolenoid1.set(false);
    	releaseSolenoid2.set(false);
    }
    public void releaseLeftRamp() {
    	releaseSolenoid1.set(false);
    }
    public void releaseRightRamp() {
    	releaseSolenoid2.set(false);
    }
    
    public void liftLeftRamp() {
    	solenoid1.set(true);
    	solenoid2.set(true);
    }
    public void liftRightRamp() {
    	solenoid3.set(true);
    	solenoid4.set(true);
    }
    
    public double getTimeRemainingInMatchPeriod(){
    	double time = DriverStation.getInstance().getMatchTime();
    	return time;
    }
    
    public void setLeftRampDeployed(){
    	leftRampDeployed = true;
    }
    
    public void setRightRampDeployed(){
    	rightRampDeployed = true;
    }
    
    public boolean getLeftRampDeployedStatus(){
    	return leftRampDeployed;
    }

    public boolean getRightRampDeployedStatus(){
    	return rightRampDeployed;
    }
    
    public static void checkIfSafetiesAreEnabled(){
    	char safetyEnabled = Robot.getRampSafetyStatus();
    	if(safetyEnabled == 'y'){
    		safetiesEnabled = true;
    	}
    	else{
    		safetiesEnabled = false;
    	}
    }
    
    public boolean returnSafetyStatus(){
    	boolean safetyStatus = safetiesEnabled;
    	return safetyStatus;
    }
    
    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

