package kinematics;

public enum MaxVelocityAndMaxAccelerationTrajectoryType {
	willCruiseAtMaxVelocityAndMaxAcceleration, willCruiseAtMaxAccelerationNotMaxVelocity, willNotCruiseAtMaxVelocityOrMaxAcceleration
}
