package kinematics;

public enum MaxVelocityAndMaxAccelerationReachability {
	willReachMaxVelocityAndMaxAcceleration, willReachMaxAccelerationNotMaxVelocity, willNotReachMaxVelocityOrMaxAcceleration, willReachMaxVelocityNotMaxAcceleration
}
